# Generated by Django 3.2.7 on 2021-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210908_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits_and_vegetables', 'Fruits And Vegetables'), ('foodgrains_oil_and_masala', 'Foodgrains Oil Masala'), ('dairy', 'Dairy'), ('beverages', 'Beverages'), ('cleaning_and_household', 'Cleaning And Household'), ('beauty_and_hygiene', 'Beauty And Hygiene'), ('snacks', 'Snacks'), ('new', 'New')], default='new', max_length=64),
        ),
    ]
