version: "3"

services:
  postgresdb:
    image: postgres:14.1-alpine
    volumes:
      - pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=projectdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
volumes:
  pgsql:
