version: "3"

services:
  db:
    image: postgres
    volumes:
      - pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=projectdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgsql:
