# Generated by Django 3.2.7 on 2021-09-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210903_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='added_by',
            new_name='user',
        ),
    ]
