# Generated by Django 3.2.8 on 2021-10-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('dispatched', 'Dispatched'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
