STORE_PERM_PREFIX = 'store.'

ADD_CART = STORE_PERM_PREFIX + 'add_cart'
READ_CART = STORE_PERM_PREFIX + 'view_cart'
UPDATE_CART = STORE_PERM_PREFIX + 'change_cart'
DELETE_CART = STORE_PERM_PREFIX + 'delete_cart'

ADD_CARTITEM = STORE_PERM_PREFIX + 'add_cartitem'
READ_CARTITEM = STORE_PERM_PREFIX + 'view_cartitem'
UPDATE_CARTITEM = STORE_PERM_PREFIX + 'change_cartitem'
DELETE_CARTITEM = STORE_PERM_PREFIX + 'delete_cartitem'

ADD_PRODUCT = STORE_PERM_PREFIX + 'add_product'
READ_PRODUCT = STORE_PERM_PREFIX + 'view_product'
UPDATE_PRODUCT = STORE_PERM_PREFIX + 'change_product'
DELETE_PRODUCT = STORE_PERM_PREFIX + 'delete_product'

AUTH_PERM_PREFIX = 'authentication.'

ADD_USER = AUTH_PERM_PREFIX + 'add_user'
READ_USER = AUTH_PERM_PREFIX + 'view_user'
UPDATE_USER = AUTH_PERM_PREFIX + 'change_user'
DELETE_USER = AUTH_PERM_PREFIX + 'delete_user'

ADD_TOKEN = AUTH_PERM_PREFIX + 'add_token'
READ_TOKEN = AUTH_PERM_PREFIX + 'view_token'
UPDATE_TOKEN = AUTH_PERM_PREFIX + 'change_token'
DELETE_TOKEN = AUTH_PERM_PREFIX + 'delete_token'

ADD_PERMISSION = AUTH_PERM_PREFIX + 'add_permission'
READ_PERMISSION = AUTH_PERM_PREFIX + 'view_permission'
UPDATE_PERMISSION = AUTH_PERM_PREFIX + 'change_permission'
DELETE_PERMISSION = AUTH_PERM_PREFIX + 'delete_permission'

ORDER_PERM_PREFIX = 'order.'

ADD_ORDER = ORDER_PERM_PREFIX + 'add_order'
READ_ORDER = ORDER_PERM_PREFIX + 'view_order'
UPDATE_ORDER = ORDER_PERM_PREFIX + 'change_order'
DELETE_ORDER = ORDER_PERM_PREFIX + 'delete_order'

ADD_ORDERITEM = ORDER_PERM_PREFIX + 'add_orderitem'
READ_ORDERITEM = ORDER_PERM_PREFIX + 'view_orderitem'
UPDATE_ORDERITEM = ORDER_PERM_PREFIX + 'change_orderitem'
DELETE_ORDERITEM = ORDER_PERM_PREFIX + 'delete_orderitem'
